<h1><?php echo $this->getHelloWorldTxt(); ?></h1>

<div id="popup-edit-product" class="hide-popup popup-for-right" data-bind="scope:'webpos_cart_editpopup'">
    <div class="form-group">
        <div class="">
            <label class="required" for="firstname"><span><?php echo __('Price') ?></span><em>*</em></label>
            <input type="text" data-bind="value:price" placeholder="<?php echo __('Price') ?>" class="form-control input-text" data-validate="{required:true}" title="Price" name="price" id="price" value="">
        </div>
        <div class="">
            <label class="required" for="lastname"><span><?php echo __('Qty') ?></span><em>*</em></label>
            <input type="text" data-bind="value:qty" placeholder="<?php echo __('Qty') ?>"  class="form-control input-text required-entry" title="Qty"  name="qty" id="qty" value="">
        </div>
        <div class="">
            <label class="required" for="total"><span><?php echo __('Total') ?></span><em>*</em></label>
            <span data-bind="text:total"></span>
        </div>
        <div class="buttons-set" >
            <button data-bind="click: loadProductArray" type="submit" title="<?php echo __('Save'); ?>" class="button button-config action primary">
                    <span>
                        <?php echo __('Save') ?>
                    </span>
            </button>
        </div>
    </div>
    <script>

        window.getListProduct = '<?php echo $this->getBaseurl().'knockoutstudy/index/inputproduct' ?>';
    </script>
<script type="text/x-magento-init">
{
"#popup-edit-product": {
   "Magento_Ui/js/core/app": {
          "components" : {
             "webpos_cart_editpopup": {
                  "component": "Magestore_Knockoutstudy/js/inputproduct",
                   "displayArea": "webpos_cart_editpopup"
              }
          }
       }
   }
}


</script>
</div>

